apiVersion: v1
kind: Service
metadata:
  name: tweetseeker-service
  labels:
    app: tweetseeker
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: tweetseeker
---
apiVersion: "v1"
kind: "Service"
metadata: 
  name: "mongodb-service"
  labels: 
    app: "mongodb"
spec: 
  ports: 
    - 
      port: 27017
      targetPort: "mongo-server"
  selector: 
    app: "mongodb"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tweetseeker
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    purpose: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweetseeker
    spec:
      containers:
      - name: tweetsweb
        image: wallnerryan/dockercon-tweets-web
        ports:
        - containerPort: 8080
          hostPort: 80
          protocol: TCP
      - name: tweetstreamer
        image: wallnerryan/dockercon-tweets-stream
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: TWITTER_TRACK
          value: "#DockerCon"
        - name: CONSUMER_KEY
          value: "<INSERT>"
        - name: CONSUMER_SECRET
          value: "<INSERT>"
        - name: ACCESS_TOKEN_KEY
          value: "<INSERT>"
        - name: ACCESS_TOKEN_SECRET
          value: "<INSERT>"
      - name: mongodb
        image: clusterhq/mongodb
        ports:
        - name: "mongo-server"
          containerPort: 27017
        volumeMounts:
          # name must match the volume name below
          - name: tweetdata
            mountPath: "/data/db"
      volumes:
        - name: tweetdata
          flocker:
            datasetName: FlockerVolume1
