apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongodb-service"
  labels:
    app: "mongodb"
spec:
  ports:
    -
      port: 27017
  selector:
    app: "mongodb"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tweetseeker-mongo
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    purpose: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweetseeker-mongo
    spec:
      containers:
      - name: mongodb
        image: clusterhq/mongodb
        ports:
          -
            containerPort: 27017
        volumeMounts:
          # name must match the volume name below
          - name: tweetdata
            mountPath: "/data/db"
      volumes:
        - name: tweetdata
          flocker:
            datasetName: FlockerVolume6
