apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongodb-service"
  labels:
    app: "tweetseeker-mongodb"
spec:
  ports:
    -
      port: 27017
      targetPort: "mongodb-port"
  selector:
    app: "tweetseeker-mongodb"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tweetseeker-mongodb
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    purpose: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweetseeker-mongodb
    spec:
      containers:
      - name: mongodb
        image: clusterhq/mongodb
        ports:
          - name: mongodb-port
            containerPort: 27017
        volumeMounts:
          # name must match the volume name below
          - name: tweetdata
            mountPath: "/data/db"
      volumes:
        - name: tweetdata
          flocker:
            datasetName: testvol004
