apiVersion: v1
kind: Service
metadata:
  name: tweetseeker-service
  labels:
    app: tweetseeker
spec:
  ports:
    # the port that this service should serve on
  - port: 8888
    targetPort: "tweetsweb1"
  selector:
    app: tweetseeker
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tweetseeker
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    purpose: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweetseeker
    spec:
      containers:
      - name: tweetsweb
        image: wallnerryan/tweets-web
        ports:
        - name: tweetsweb1
          containerPort: 8080
          hostPort: 8888
          protocol: TCP
        env:
        - name: MONGODB_SERVICE_SERVICE_HOST
          value: "<insert mongodb service ep>"
      - name: tweetstreamer
        image: wallnerryan/tweets-stream
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: TWITTER_TRACK
          value: "#twitter"
        - name: CONSUMER_KEY
          value: "<INSERT>"
        - name: CONSUMER_SECRET
          value: "<INSERT>"
        - name: ACCESS_TOKEN_KEY
          value: "<INSERT>"
        - name: ACCESS_TOKEN_SECRET
          value: "<INSERT>"
        - name: MONGODB_SERVICE_SERVICE_HOST
          value: "<insert mongodb service ep>"
